App_Acara/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('acara/', acara, name='acara'),
    path('acara/add', acara_add, name='acara_add')
]

App_Login/urls.py
from django.urls import path, include
from .views import index

app_name = 'login_page'

urlpatterns = [
    path('', index, name='index')
]

App_Sepeda/urls.py
from django.urls import path, include
from .views import *

app_name = 'App_Sepeda'

urlpatterns = [
    path('bike/', sepeda, name='bike'),
    path('bike/create/', create, name='create'),
    path('bike/update/', update, name='update'),
]

App_Stasiun/urls.py
from django.urls import path, include
from .views import *

app_name = 'App_Stasiun'

urlpatterns = [
    path('station/', stasiun, name='stasiun'),
    path('station/create/', create, name='create'),
    path('station/update/', update, name='update'),
]

App_Voucher/urls.py
from django.urls import path, include
from .views import *

app_name = 'App_Voucher'

urlpatterns = [
    path('voucher/', voucher, name='voucher'),
    path('peminjaman/', peminjaman, name='peminjaman'),
    path('addvoucher/', addvoucher, name='addvoucher'),
    path('updatevoucher/', updatevoucher, name='updatevoucher'),
    path('createpeminjaman/', createpeminjaman, name='createpeminjaman')
]

BikeSharing/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_HomePage.urls')),
    path('', include('App_Voucher.urls')),
    path('', include('App_Stasiun.urls')),
    path('', include('App_Sepeda.urls')),
    path('registration/', include('App_Registration.urls')),
    path('login/', include('App_Login.urls')),
    path('transaction/', include('App_Transaction.urls')),
    path('report/', include('App_Report.urls')),
    path('', include('App_Acara.urls')),
    path('', include('App_Penugasan.urls')),
]

templates/partials/footer.html
<footer class="footer-distributed">

    <div class="footer-left">

        <h3>Bike<span>Sharing</span></h3>

        <p class="footer-links">
            <a href="#">Home</a>
            ·
            <a href="#">Donate</a>
            ·
            <a href="#">About</a>
            ·
            <a href="#">FAQ</a>
            ·
            <a href="#">Testimony</a>
        </p>

        <p class="footer-company-name">BikeSharing &copy; 2019</p>
    </div>

    <div class="footer-center">

        <div>
            <i class="fa fa-map-marker"></i>
            <p><span>Jalan Fasilkom</span> Depok, Jawa Barat</p>
        </div>

        <div>
            <i class="fa fa-phone"></i>
            <p>+1 1111111111</p>
        </div>

        <div>
            <i class="fa fa-envelope"></i>
            <p><a href="mailto:support@company.com">bikesharing@company.com</a></p>
        </div>

    </div>

    <div class="footer-right">

        <p class="footer-company-about">
            <span>ABOUT US</span>
            Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor lacus vehicula sit amet.
        </p>

        <div class="footer-icons">

            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-github"></i></a>

        </div>

    </div>

</footer>

templates/partials/header.html
{% load static from staticfiles %}
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
        <a class="navbar-brand" href="{% url 'App_HomePage:index' %}"><img class="img-responsive" alt = "Logo BikeSharing" src= "{% static 'img/Logo BikeSharing.png' %}"/></a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class=""><a href="{% url 'App_HomePage:index' %}">HOME</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">STATION <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'App_Stasiun:create' %}">Create Station</a></li>
              <li><a href="{% url 'App_Stasiun:stasiun' %}">Station List</a></li>
            </ul>
          </li>
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">BIKE <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'App_Sepeda:create' %}">Create Bike</a></li>
                <li><a href="{% url 'App_Sepeda:bike' %}">Bike List</a></li>
              </ul>
            </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> EVENT <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li class="dropdown-header">Nav header</li>
              <li><a href="#">Separated link</a></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> VOUCHER <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'App_Voucher:addvoucher' %}">Add Voucher</a></li>
                <li><a href="{% url 'App_Voucher:voucher' %}">List Voucher</a></li>
              </ul>
          </li>
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> PEMINJAMAN <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'App_Voucher:createpeminjaman' %}">Buat Peminjaman</a></li>
                <li><a href="{% url 'App_Voucher:peminjaman' %}">List Peminjaman</a></li>
              </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="far fa-user-circle"></i> USER <span class="caret"></span></a>
              <ul class="dropdown-menu">
                {% if user.is_authenticated %}
                <li><a href="{% url 'login_page:index' %}"><span class="glyphicon glyphicon-log-in"></span>  Login</a></li>
                <li><a href="{% url 'regist_page:index' %}"><span class="glyphicon glyphicon-user"></span>  Register</a></li>
                </li>
                {% else %}
                  <li><a href="{% url 'login_page:index' %}"><span class="glyphicon glyphicon-log-in"></span>  Login</a></li>
                  <li><a href="{% url 'regist_page:index' %}"><span class="glyphicon glyphicon-user"></span>  Register</a></li>
                {% endif %}
              </ul>
            </li>  
        </ul>
  
      </div>
      <!--/.nav-collapse -->
    </div>
    <!--/.container-fluid -->
  </nav>