App_Acara/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('acara/', acara, name='acara'),
    path('acara/add', acara_add, name='acara_add')
]

App_Transaction/urls.py
from django.urls import path, include
from .views import list_transaction

app_name = 'transaction_page'

urlpatterns = [
    path('', list_transaction, name='list_transaction')
]

App_Voucher/urls.py
from django.urls import path, include
from .views import *

app_name = 'App_Voucher'

urlpatterns = [
    path('voucher/', voucher, name='voucher'),
    path('peminjaman/', peminjaman, name='peminjaman'),
    path('addvoucher/', addvoucher, name='addvoucher'),
    path('updatevoucher/', updatevoucher, name='updatevoucher'),
    path('createpeminjaman/', createpeminjaman, name='createpeminjaman')
]

BikeSharing/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_HomePage.urls')),
    path('', include('App_Voucher.urls')),
    path('', include('App_Stasiun.urls')),
    path('', include('App_Sepeda.urls')),
    path('registration/', include('App_Registration.urls')),
    path('login/', include('App_Login.urls')),
    path('transaction/', include('App_Transaction.urls')),
    path('report/', include('App_Report.urls')),
    path('', include('App_Acara.urls')),
    path('', include('App_Penugasan.urls')),
]

App_Voucher/models.py
from django.db import models

# Create your models here.

App_Voucher/forms.py
from django import forms

class AddVoucherForm(forms.Form):
    nama = forms.CharField(label = '', max_length = 30, widget=forms.TextInput(attrs={
        "class" : "fields",
        "placeholder" : "Nama",
        "required" : True
    }))
    kategori = forms.CharField(label = '',  max_length = 30, widget=forms.TextInput(attrs={
        "class" : "fields",
        "placeholder" : "Kategori",
        "required" : True
    }))
    nilai_poin = forms.CharField(label = '', max_length = 20, widget=forms.TextInput(attrs={
        "class" : "fields",
        "placeholder" : "Nilai Poin",
        "required" : True
    }))
    deskripsi = forms.CharField(label = '', max_length = 300, widget=forms.TextInput(attrs={
        "class" : "fields",
        "placeholder" : "Deskripsi",
        "required" : True
    }))
    jumlah = forms.CharField(label = '', max_length = 30, widget=forms.TextInput(attrs={
        "class" : "fields",
        "placeholder" : "Jumlah",
        "required" : True
    }))

class UpdateVoucherForm(forms.Form):
    nama = forms.CharField(label = '', max_length = 30, widget=forms.TextInput(attrs={
        "class" : "fields",
        "placeholder" : "Nama",
        "required" : True
    }))
    kategori = forms.CharField(label = '',  max_length = 30, widget=forms.TextInput(attrs={
        "class" : "fields",
        "placeholder" : "Kategori",
        "required" : True
    }))
    nilai_poin = forms.CharField(label = '', max_length = 20, widget=forms.TextInput(attrs={
        "class" : "fields",
        "placeholder" : "Nilai Poin",
        "required" : True
    }))
    deskripsi = forms.CharField(label = '', max_length = 300, widget=forms.TextInput(attrs={
        "class" : "fields",
        "placeholder" : "Deskripsi",
        "required" : True
    }))
PILIHAN_STASIUN = [
    ('1', 'Stasiun Basdat Depok 1'),
    ('2', 'Stasiun Basdat Depok 2'),
    ('3', 'Stasiun Basdat Depok 3'),
    ('4', 'Stasiun Basdat Depok 4'),
    ('5', 'Stasiun Basdat Depok 5'),
    ('6', 'Stasiun Basdat Depok 6'),
    ('7', 'Stasiun Basdat Depok 7'),
    ('8', 'Stasiun Basdat Depok 8')
]
class CreatePeminjamanForm(forms.Form):
    Sepeda_stasiun = forms.CharField(label = '', max_length = 30, widget=forms.Select(choices=PILIHAN_STASIUN))

App_Voucher/views.py
from django.shortcuts import render, redirect
from .forms import *
# Create your views here.

def voucher(req):
    return render(req, 'voucher.html')

def peminjaman(req):
    return render(req, 'peminjaman.html')

def addvoucher(req):
    form = AddVoucherForm()
    if req.method == 'POST':
        return redirect('/voucher/')
    return render(req, 'addvoucher.html', {'form' : form})

def updatevoucher(req):
    form = UpdateVoucherForm()
    if req.method == 'POST':
        return redirect('/voucher/')
    return render(req, 'updatevoucher.html', {'form' : form})
    

def createpeminjaman(req):
    form = CreatePeminjamanForm()
    if req.method == 'POST':
        return redirect('/peminjaman/')
    return render(req, 'createpeminjaman.html', {'form' : form})

App_Voucher/templates/addvoucher.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'vstyles.css' %}">
    <h1 class="text-center tabelgan">Form Penambahan Voucher</h1>
        <form method="POST">
            {% csrf_token %}
            {{form}}
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
{% endblock %}

App_Voucher/templates/createpeminjaman.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'vstyles.css' %}">
    <h1 class="text-center tabelgan">Form Buat Peminjaman</h1>
    <div class="pleir">
        <h4>Sepeda Stasiun : </h4>
        <form method="POST">
                {% csrf_token %}
                {{form}}
                <input type="submit" class="btn btn-primary" value="Submit">
        </form>
    </div>
{% endblock %}

App_Voucher/templates/peminjaman.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'vstyles.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- MDB core JavaScript -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <script src = "{% static 'mdb/js/mdb.min.js' %}" type = "text/javascript"></script>
    <link rel = "stylesheet" href = "{% static 'mdb/css/addons/datatables.min.css' %}">
    <script src = "{% static 'mdb/js/addons/datatables.min.js' %}" type = "text/javascript"></script>
    <script src = "{% static 'paginationscripts.js' %}" type = "text/javascript"></script>

    <h1 class="text-center tabelgan">Daftar Sepeda</h1>
    <table class="table" id="dtBasicExample">
        <thead>
            <tr>
                <th scope="col">Nomor Kartu Anggota</th>
                <th scope="col">Sepeda</th>
                <th scope="col">Stasiun</th>
                <th scope="col">Waktu Kembali</th>
                <th scope="col">Biaya</th>
                <th scope="col">Denda</th>
                <th scope="col">Action [Anggota]</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">13u78q</th>
                <td>11244-BMX</td>
                <td>637-Stasiun X</td>
                <td>Stasiun Basdat Depok 1</td>
                <td>-</td>
                <td>-</td>
                <td><a href="{% url 'transaction_page:list_transaction' %}"><button type="button" class="btn btn-primary tombolgan">Kembalikan</button></a><br>
            </tr>
            <tr>
                <th scope="row">13u78r</th>
                <td>11244-BMY</td>
                <td>637-Stasiun Y</td>
                <td>Stasiun Basdat Depok 2</td>
                <td>-</td>
                <td>-</td>
                <td><a href="{% url 'transaction_page:list_transaction' %}"><button type="button" class="btn btn-primary tombolgan">Kembalikan</button></a><br>
            </tr>
        </tbody>
    </table>
{% endblock %}

App_Voucher/templates/updatevoucher.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'vstyles.css' %}">
    <h1 class="text-center tabelgan">Form Update Voucher</h1>
        <form method="POST">
            {% csrf_token %}
            {{form}}
            <input type="submit" class="btn btn-primary" value="Update">
        </form>
{% endblock %}

App_Voucher/templates/voucher.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'vstyles.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- MDB core JavaScript -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <script src = "{% static 'mdb/js/mdb.min.js' %}" type = "text/javascript"></script>
    <link rel = "stylesheet" href = "{% static 'mdb/css/addons/datatables.min.css' %}">
    <script src = "{% static 'mdb/js/addons/datatables.min.js' %}" type = "text/javascript"></script>
    <script src = "{% static 'paginationscripts.js' %}" type = "text/javascript"></script>

    <h1 class="text-center tabelgan">Daftar Voucher</h1>
    <table class="table" id="dtBasicExample">
        <thead>
            <tr>
                <th scope="col">ID Voucher</th>
                <th scope="col">Nama</th>
                <th scope="col">Kategori</th>
                <th scope="col">Nilai Poin</th>
                <th scope="col">Deskripsi</th>
                <th scope="col">Diklaim oleh</th>
                <th scope="col">Action [Admin]</th>
                <th scope="col">Action [Anggota]</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1111q</th>
                <td>Voucher Belanja</td>
                <td>Belanja</td>
                <td>300</td>
                <td>Gratis Belanja</td>
                <td>-</td>
                <td><a href="{% url 'App_Voucher:updatevoucher' %}"><button type="button" class="btn btn-primary tombolgan">Update</button></a><br>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Delete</button>
                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Konfirmasi</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Apakah anda yakin ingin menghapus voucher ini?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-primary" data-dismiss="modal">Ya</button>
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
                                </div>
                                </div>
                            </div>
                            </div>
                </td>
                <td>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal2">Klaim</button>
                    <div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Pemberitahuan</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Selamat ! Voucher ini telah anda klaim dan menjadi milik anda !
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
                                </div>
                                </div>
                            </div>
                            </div>
                </td>
            </tr>
            <tr>
                <th scope="row">95675</th>
                <td>Voucher Makan</td>
                <td>Makan</td>
                <td>100</td>
                <td>Makan Gratis</td>
                <td>1w44-<br>Nunung</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                    <th scope="row">1111r</th>
                    <td>Voucher Belanja</td>
                    <td>Belanja</td>
                    <td>300</td>
                    <td>Gratis Belanja</td>
                    <td>-</td>
                    <td><a href="{% url 'App_Voucher:updatevoucher' %}"><button type="button" class="btn btn-primary tombolgan">Update</button></a><br>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Delete</button>
                    </td>
                    <td>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal2">Klaim</button>
                    </td>
            </tr>
            <tr>
                    <th scope="row">1112q</th>
                    <td>Voucher Belanja</td>
                    <td>Belanja</td>
                    <td>300</td>
                    <td>Gratis Belanja</td>
                    <td>-</td>
                    <td><a href="{% url 'App_Voucher:updatevoucher' %}"><button type="button" class="btn btn-primary tombolgan">Update</button></a><br>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Delete</button>
                    </td>
                    <td>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal2">Klaim</button>
                    </td>
            </tr>
            <tr>
                    <th scope="row">1121q</th>
                    <td>Voucher Belanja</td>
                    <td>Belanja</td>
                    <td>300</td>
                    <td>Gratis Belanja</td>
                    <td>-</td>
                    <td><a href="{% url 'App_Voucher:updatevoucher' %}"><button type="button" class="btn btn-primary tombolgan">Update</button></a><br>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Delete</button>
                    </td>
                    <td>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal2">Klaim</button>
                    </td>
            </tr>
            <tr>
                    <th scope="row">1211q</th>
                    <td>Voucher Belanja</td>
                    <td>Belanja</td>
                    <td>300</td>
                    <td>Gratis Belanja</td>
                    <td>-</td>
                    <td><a href="{% url 'App_Voucher:updatevoucher' %}"><button type="button" class="btn btn-primary tombolgan">Update</button></a><br>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Delete</button>
                    </td>
                    <td>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal2">Klaim</button>
                    </td>
            </tr>
            <tr>
                    <th scope="row">2111q</th>
                    <td>Voucher Belanja</td>
                    <td>Belanja</td>
                    <td>300</td>
                    <td>Gratis Belanja</td>
                    <td>-</td>
                    <td><a href="{% url 'App_Voucher:updatevoucher' %}"><button type="button" class="btn btn-primary tombolgan">Update</button></a><br>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Delete</button>
                    </td>
                    <td>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal2">Klaim</button>
                    </td>
            </tr>
            <tr>
                    <th scope="row">xfhdfda</th>
                    <td>Voucher Makan</td>
                    <td>Makan</td>
                    <td>300</td>
                    <td>Makan Gratis</td>
                    <td>-</td>
                    <td><a href="{% url 'App_Voucher:updatevoucher' %}"><button type="button" class="btn btn-primary tombolgan">Update</button></a><br>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Delete</button>
                    </td>
                    <td>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal2">Klaim</button>
                    </td>
            </tr>
            <tr>
                    <th scope="row">xfhda</th>
                    <td>Voucher Makan</td>
                    <td>Makan</td>
                    <td>300</td>
                    <td>Makan Gratis</td>
                    <td>-</td>
                    <td><a href="{% url 'App_Voucher:updatevoucher' %}"><button type="button" class="btn btn-primary tombolgan">Update</button></a><br>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Delete</button>
                    </td>
                    <td>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal2">Klaim</button>
                    </td>
            </tr>
            <tr>
                    <th scope="row">hdfda</th>
                    <td>Voucher Makan</td>
                    <td>Makan</td>
                    <td>300</td>
                    <td>Makan Gratis</td>
                    <td>-</td>
                    <td><a href="{% url 'App_Voucher:updatevoucher' %}"><button type="button" class="btn btn-primary tombolgan">Update</button></a><br>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Delete</button>
                    </td>
                    <td>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal2">Klaim</button>
                    </td>
            </tr>
            <tr>
                    <th scope="row">xfhdwea</th>
                    <td>Voucher Makan</td>
                    <td>Makan</td>
                    <td>300</td>
                    <td>Makan Gratis</td>
                    <td>-</td>
                    <td><a href="{% url 'App_Voucher:updatevoucher' %}"><button type="button" class="btn btn-primary tombolgan">Update</button></a><br>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Delete</button>
                    </td>
                    <td>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal2">Klaim</button>
                    </td>
            </tr>
        </tbody>
    </table>
{% endblock %}